export const ADD_EMPLOYEE_RECORD = "ADD_EMPLOYEE_RECORD";
export const UPDATE_EMPLOYEE_RECORD = "UPDATE_EMPLOYEE_RECORD"
export const DELETE_EMPLOYEE_RECORD = "DELETE_EMPLOYEE_RECORD";
export const GET_EMPLOYEE_RECORD = "GET_EMPLOYEE_RECORD";
export const LIST_EMPLOYEES = "LIST_EMPLOYEES";
